# Tencent is pleased to support the open source community by making Polaris available.
#
# Copyright (C) 2019 THL A29 Limited, a Tencent company. All rights reserved.
#
# Licensed under the BSD 3-Clause License (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://opensource.org/licenses/BSD-3-Clause
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.

version: '3.9'

networks:
  backend:
    driver: bridge

volumes:
  vlm_data_mysql:
    external: true

services:
  sergo-server:
    container_name: sergo-server
    hostname: sergo-server
    image: polarismesh/sergo-server:##POLARIS_SERVER_VERSION##
    restart: always
    volumes:
      - ./server/sergo-server.yaml:/root/conf/sergo-server.yaml
    expose: # 用于北极星集群内部访问
      - 8090    # api-http
      - 8091    # service-grpc
      - 8093    # config-grpc
      - 8761    # service-eureka
      - 8848    # nacos-http port
      - 9848    # nacos-grpc port
      - 15010   # xds-v3
    ports: # 用于其他服务访问北极星
      - "8090:8090" # api-http
      - "8091:8091" # service-grpc
      - "8093:8093" # config-grpc
      - "8761:8761" # service-eureka
      - "8848:8848" # nacos-http port
      - "9848:9848" # nacos-grpc port
      - "15010:15010" # xds-v3
    networks:
      - backend
    links:
      - mysql
    depends_on:
      - mysql
  polaris-console:
    container_name: polaris-console
    hostname: polaris-console
    image: GovernSea/sergo-server-console:##POLARIS_CONSOLE_VERSION##
    restart: always
    volumes:
      - ./console/polaris-console.yaml:/root/polaris-console.yaml
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - sergo-server
      - pushgateway
    links:
      - sergo-server
      - pushgateway
  polaris-limiter:
    container_name: polaris-limiter
    hostname: polaris-limiter
    image: GovernSea/sergo-server-limiter:##POLARIS_LIMITER_VERSION##
    restart: always
    environment:
      - MY_ID=1
    volumes:
      - ./limiter/polaris-limiter.yaml:/root/polaris-limiter.yaml
    expose: # 用于北极星集群内部访问
      - 8100    # service-http
      - 8101    # service-grpc
    ports:
      - "8100:8100"
      - "8101:8101"
    networks:
      - backend
    depends_on:
      - sergo-server
    links:
      - sergo-server
  mysql:
    build: mysql
    container_name: mysql
    hostname: mysql
    platform: linux/amd64
    restart: always
    command: mysqld --optimizer-trace-max-mem-size=102400 --default-authentication-plugin=mysql_native_password
    environment:
      - TZ=Asia/Shanghai
      - LANG=zh_CN.utf8
      - MYSQL_DATABASE=polaris_server
      - MYSQL_USER=default
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=polaris
    volumes:
      - vlm_data_mysql:/var/lib/mysql
      - ./mysql/mysqld.cnf:/etc/mysql/conf.d/custom.cnf:cached
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    expose:
      - 3306
    networks:
      - backend
  prometheus:
    container_name: prometheus
    hostname: polaris-prometheus
    build: prometheus
    restart: always
    networks:
      - backend
    expose:
      - 9090
    links:
      - sergo-server # 采集北极星性能
  pushgateway:
    container_name: polaris-pushgateway
    image: prom/pushgateway:latest
    hostname: polaris-pushgateway
    restart: always
    networks:
      - backend
    expose:
      - 9091
  grafana:
    container_name: polaris-grafana
    build: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/:rw
      - ./grafana/dashboards:/etc/grafana/dashboards/:rw
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:rw
    depends_on:
      - prometheus
      - pushgateway
    networks:
      - backend
