apiVersion: v1
data:
  polaris-console.yaml: |-
    logger:
      RotateOutputPath: log/polaris-console.log
      RotationMaxSize: 500
      RotationMaxAge: 30
      RotationMaxBackups: 100
      level: info
    webServer:
      mode: "release"
      listenIP: "0.0.0.0"
      listenPort: 8080
      jwt:
        secretKey: "polarismesh@2021"
        expired: 1800
      namingV1URL: "/naming/v1"
      namingV2URL: "/naming/v2"
      authURL: "/core/v1"
      requestURL: "/naming/v1"
      configURL: "/config/v1"
      monitorURL: "/api/v1"
      webPath: "web/dist/"
    polarisServer:
      address: "127.0.0.1:8090"
      polarisToken: "polaris@12345678"
    monitorServer:
      address: "polaris-prometheus:9090"
kind: ConfigMap
metadata:
  name: polaris-console-config
  namespace: polaris-system
