# apiserver plugin name
- name: service-eureka
  # apiserver additional configuration
  option:
    # tcp server listen ip
    listenIP: "0.0.0.0"
    # tcp server listen port
    listenPort: 8761
    # set the polaris namingspace of the EUREKA service default
    namespace: default
    # pull data from the cache of the polaris, refresh the data cache in the Eureka protocol
    refreshInterval: 10
    # eureka incremental instance changes time cache expiration cycle
    deltaExpireInterval: 60
    # unhealthy instance expiration cycle
    unhealthyExpireInterval: 180
    # whether to enable an instance ID of polaris to generate logic
    generateUniqueInstId: false
    # TCP connection number limit
    connLimit:
      # Whether to turn on the TCP connection limit function, default FALSE
      openConnLimit: false
      # The number of connections with the most IP
      maxConnPerHost: 1024
      # Current Listener's maximum number of connections
      maxConnLimit: 10240
      # Whitening list ip list, English comma separation
      whiteList: 127.0.0.1
      # Cleaning the cycle of link behavior
      purgeCounterInterval: 10s
      # How long does the unpretentious link clean up
      purgeCounterExpired: 5s
- name: api-http
  option:
    listenIP: "0.0.0.0"
    listenPort: 8090
    # debug pprof switch
    enablePprof: true
    # swagger docs switch
    enableSwagger: true
    connLimit:
      openConnLimit: false
      maxConnPerHost: 128
      maxConnLimit: 5120
      whiteList: 127.0.0.1
      purgeCounterInterval: 10s
      purgeCounterExpired: 5s
    # Referenced from: [Pull Requests 387], in order to improve the processing of service discovery QPS when using api-http server
    enableCacheProto: false
    # Cache default size
    sizeCacheProto: 128
  # Set the type of open API interface
  api:
    # admin OpenAPI interface
    admin:
      enable: true
    # Console OpenAPI interface
    console:
      enable: true
      # OpenAPI group that needs to be exposed
      include: [default, service, config]
    # client OpenAPI interface
    client:
      enable: true
      include: [discover, register, healthcheck, config]
  # Polaris is a client protocol layer based on the gRPC protocol, which is used for registration discovery and service governance rule delivery
- name: service-grpc
  option:
    listenIP: "0.0.0.0"
    listenPort: 8091
    connLimit:
      openConnLimit: false
      maxConnPerHost: 128
      maxConnLimit: 5120
    # Open the protobuf parsing cache, cache the protobuf serialization results of the same content, and improve the processing of service discovery QPS
    enableCacheProto: true
    # Cache default size
    sizeCacheProto: 128
    # tls setting
    tls:
      # set cert file path
      certFile: ""
      # set key file path
      keyFile: ""
      # set trusted ca file path
      trustedCAFile: ""
  api:
    client:
      enable: true
      include: [discover, register, healthcheck]
- name: config-grpc
  option:
    listenIP: "0.0.0.0"
    listenPort: 8093
    connLimit:
      openConnLimit: false
      maxConnPerHost: 128
      maxConnLimit: 5120
  api:
    client:
      enable: true
- name: xds-v3
  option:
    listenIP: "0.0.0.0"
    listenPort: 15010
    connLimit:
      openConnLimit: false
      maxConnPerHost: 128
      maxConnLimit: 10240
- name: service-nacos
  option:
    listenIP: "0.0.0.0"
    listenPort: 8848
    # Set the nacos default namespace to correspond to the Polaris namespace information
    defaultNamespace: default
    connLimit:
      openConnLimit: false
      maxConnPerHost: 128
      maxConnLimit: 10240
- name: service-apollo
  option:
    listenIP: "0.0.0.0"
    listenPort: 8890
    connLimit:
      openConnLimit: false
      maxConnPerHost: 128
      maxConnLimit: 10240
