apiVersion: v1
kind: Service
metadata:
  name: pole-greptimedb
  namespace: pole-system
  labels:
    app.kubernetes.io/name: pole-greptimedb
    app.kubernetes.io/part-of: pole
spec:
  type: ExternalName
  externalName: maas-greptimedb-frontend.tidemind.svc.cluster.local
  ports:
    - name: http
      port: 4000
    - name: grpc
      port: 4001
    - name: mysql
      port: 4002
    - name: postgres
      port: 4003
